x11-libs/gtk+/gtk+-3.22.0.ebuild

The ebuild uses eapply, which was added in EAPI 6. Using EAPI 5 prevents gtk+-3.16.2-remove_update-icon-cache.patch from being applied, which creates a file collision if gtk2 is also installed.

x11-libs/gtk+-3.22.0: Bump EAPI to 6

---

gnome-base/gnome-desktop/gnome-desktop-3.24.0.ebuild

Fails to configure/build if gdk-pixbuf is below 2.36.5

[gnome-desktop] 3.24 dependency requirements

---

gnome-base/nautilus/nautilus-3.24.0.ebuild

Fails to configure/build without updated dependencies ( `app-arch/gnome-autoar` `dev-libs/glib` )

[gnome-base/nautilus] 3.24 dependency update

---

gnome-base/gnome-control-center/gnome-control-center-3.24.0.ebuild
gnome-base/libgtop/libgtop-2.36.0.ebuild

I don't actually know if this is the correct method for doing this, however this is the way I have succeeded in getting these two packages to compile. Without this, it fails with a message about assignment before a for loop not being allowed and suggests changing `-std` to C99 or C11 (or gnu variants).
(Also there's no change in the Manifests when I do this for whatever reason.)

Add CFLAGS -std=gnu11 in ebuild

---

app-misc/tracker/tracker-1.12.0.ebuild

seccomp is now mandatory on Linux.
https://git.gnome.org/browse/tracker/commit/?id=397e1e00c455babaa1d6e65f04e1f7145020731e
https://git.gnome.org/browse/tracker/commit/?id=bdf25c78ee11e25bf017e37c78f7c07a2f7ac29a

tracker: Add sys-libs/libseccomp to RDEPEND

---

gnome-base/gnome-control-center/gnome-control-center-3.24.1.ebuild
gnome-base/libgtop/libgtop-2.36.0.ebuild
www-client/epiphany/epiphany-3.24.1.ebuild

- Adds `-std=gnu11` to `www-client/epiphany`
```ephy-filters-manager.c: In function ‘remove_old_adblock_filters’:
ephy-filters-manager.c:207:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
for (GList *l = current_files; l != NULL; l = l->next) {
^
ephy-filters-manager.c:207:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
ephy-filters-manager.c: In function ‘update_adblock_filter_files’:
ephy-filters-manager.c:244:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
for (guint i = 0; filters[i]; i++) {
^
make[4]: *** [Makefile:801: libephymisc_la-ephy-filters-manager.lo] Error 1
```
```
$ gcc --version
gcc (Gentoo 4.9.4 p1.0, pie-0.6.4) 4.9.4
```
- Changes other packages (`gnome-control-center`, …

Alter CFLAGS of some packages to build with <gcc-5

---

gnome-base/gnome-control-center/gnome-control-center-3.24.1.ebuild
gnome-base/libgtop/libgtop-2.36.0.ebuild
www-client/epiphany/epiphany-3.25.1.ebuild

GCC v5 has been stablized in the gentoo tree, making CFLAG adjustments unnecessary.

Revert cflags

---

dev-libs/gmime/gmime-3.0.0.ebuild

Packages such as `dev-libs/totem-pl-parser-3.10.7` require gmime-2.6; but because this overlay puts v3.0.0 into the 2.6 slot, the package is upgraded. The totem package's DEPENDS allow 3.0 to be installed, and so when it is being built it fails.
~~I don't know if changing the slot of gmime is the correct solution (obviously the totem package's dependencies are not specific enough), but~~ does it make sense for gmime v3.0.0 to be in a 3.0 slot since the package does already have slots for its versions? I have both versions installed currently, and so far nothing has exploded.

[dev-libs/gmime] v3.0.0 slot change (2.6 -> 3.0)

---

net-misc/networkmanager/networkmanager-1.8.0-r1.ebuild

Please confirm whether this issue exists for anyone besides me?
---
Many file require `nm-core-enum-types.h`, however this file does not exist during build.
```
$ emerge ....
....
x86_64-pc-linux-gnu-gcc -m32 -DHAVE_CONFIG_H -I. -I/var/tmp/portage/net-misc/networkmanager-1.8.0/work/NetworkManager-1.8.0  -pthread -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib32/glib-2.0/include  -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_32 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -I/var/tmp/portage/net-misc/networkmanager-1.8.0/work/NetworkManager-1.8.0/shared -I./shared -I/var/tmp/portage/net-misc/networkmanager-1.8.0/work/NetworkManager-1.8.0/libnm-core -I./libnm-core -DG_LOG_DOMAIN=\""nm-dhcp-helper"\" -DNMRUNDIR=\"/run/NetworkManager\"   -fdata-sections -ffunction-sections …
```

[networkmananger] 1.8.0 unstabilize for build issues

---

gnome-extra/nm-applet/nm-applet-1.8.0.ebuild

```
...
checking for LIBNM_GLIB... no
configure: error: in `/var/tmp/portage/gnome-extra/nm-applet-1.8.0/work/network-manager-applet-1.8.0':
configure: error: Requested 'NetworkManager >= 1.7' but version of NetworkManager is 1.6.2
Requested 'libnm-glib >= 1.7' but version of libnm-glib is 1.6.2
Requested 'libnm-util >= 1.7' but version of libnm-util is 1.6.2
Requested 'libnm-glib-vpn >= 1.7' but version of libnm-glib-vpn is 1.6.2
...
```

[nm-applet] depend on >=networkmanager-1.7

---

gnome-extra/evolution-data-server/evolution-data-server-3.25.2.ebuild

```
-- Checking for modules 'gio-2.0;libical>=2.0;libsoup-2.4;libxml-2.0;libsecret-1'
--
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
CMakeLists.txt:885 (pkg_check_modules)
```

[evolution-data-server] Update libical dependency

---

dev-python/pygobject/pygobject-3.26.0.ebuild

new version required:
m4_define(pycairo_required_version, 1.11.1)

dev-python/pygobject: fix required pycairo dependency version

---

gnome-extra/gnome-calendar/gnome-calendar-3.27.2.ebuild

gnome-extra/gnome-calendar: add libdazzle dependency

---

eclass/gnome2-live.eclass

As for now git-r3 diswants to fetch from 'git://' urls, each time warning about necessarity to use https instead.

Move gnome2-live eclass to https

---

net-libs/webkit-gtk/webkit-gtk-2.19.3.ebuild
net-libs/webkit-gtk/webkit-gtk-2.4.11-r300.ebuild

I've switched to ruby25, this caused me to pull ruby24 back in deps.

add ruby25 to webkit-gtk

---

gnome-base/dconf/dconf-0.27.1.ebuild

dconf's compilition needs vala's command valac,or there will be an error occurs.

add vala to dconf's build dependency

---

gnome-base/nautilus/nautilus-9999.ebuild

Nautilus 3.27.2 has an annoying bug of crashing whenever you rename a file.
I've created the 9999 ebuild.
There has been some changes to the meson options, I don't know if it is all right.
I've fixed a tracker dependency, now it needs tracker-2, and a selinux dependency.
It should need some more cleanups but at least it works.

gnome-base/nautilus: creating live ebuild.

---

gnome-base/gnome-shell/gnome-shell-3.27.91.ebuild
gnome-base/gnome-shell/gnome-shell-9999.ebuild

as we can see:
https://github.com/GNOME/gnome-shell/blob/master/meson_options.txt
there is no bluetooth option, so it has been dropped in the meson options in the ebuild.
other build options has changed name.
I don't use networkmanager and the previous ebuild version was failing to disable it.
options also are required to be true/false.

gnome-base/gnome-shell: fix meson build options

---

gnome-base/gnome-settings-daemon/gnome-settings-daemon-3.28.0.ebuild

use flags are not correctly applied to the meson configure, updating accordingly.
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/meson_options.txt
I was previously using gnome without networkmanager but now is required.
option('network_manager', type: 'boolean', value: true, description: 'build with NetworkManager support (not optional on Linux platforms)')
For this reason I've also added + on networkmanager use-flag.
Some other ebuilds need these kind of update.

gnome-settings-daemon: meson build options updated.

---

gnome-base/gnome-keyring/gnome-keyring-3.28.0.1.ebuild

I got this configure error:
```
configure: error: Package requirements (gcr-3 >= 3.27.90) were not met
```

gnome-keyring: fix version of gcr dependency

---

gnome-base/gnome-shell/gnome-shell-3.28.0.ebuild

Without that version constraint you could run into:
```
Native dependency 'mutter-clutter-2' not found
```
if e.g. your mutter version is too old.

gnome-shell: fix mutter version constraint

---

gnome-base/gvfs/gvfs-1.37.1-r3.ebuild

fix gvfs useflag name as EvaSDK pointed out here:
https://github.com/Heather/gentoo-gnome/pull/247

gnome-base/gvfs: fix useflag name

---

net-libs/glib-networking/glib-networking-2.57.2.ebuild

build fails without at least this version

add meson dependency

---

x11-wm/mutter/mutter-3.30.0.ebuild

mutter-3.30.0 requires at least wayland-protocols-1.16

mutter-3.30.0 requires wayland-protocols-1.16

---

gnome-base/librsvg/librsvg-2.44.9.ebuild

Sadly, virtual/rust doen't do multilib, this is next best thing
Solves issue #279 - Change concrete Rust dependencies to virtual

Allow binary Rust, use virtual Cargo ebuild

---

gnome-base/nautilus/nautilus-3.30.4.ebuild

introspection USE flag has been reintroduced in GNOME and also in main
Gentoo tree
Bug: https://bugs.gentoo.org/665354#c6

gnome-base/nautilus: reintroduce introspection

---

app-i18n/ibus/ibus-1.5.19-r2.ebuild

The release ibus version doesn't support any vala version newer than
0.36 currently.

app-i18n/ibus: clamp vala version

---

net-libs/libsoup/libsoup-2.65.90.ebuild

It wants underscore and quotes, otherwise it takes a fallback value from
meson_options.txt and/or expands the macro in code to raw characters
like a variable name instead of a string.

libsoup: Fix ntlm_auth option behind USE=samba

---

dev-libs/gjs/gjs-1.56.0.ebuild

gjs can use spidermonkey-60.5.2_p0-r1 in gentoo tree. After updating spidermonkey gjs must be rebuilt or it/gnome-shell segfaults. I don't know how to enforce the rebuild, but can confirm it works with the in tree version.

gjs: use slot dep on spidermonkey

---

gnome-base/gnome-control-center/gnome-control-center-3.32.0.1.ebuild
gnome-base/gnome-settings-daemon/gnome-settings-daemon-3.32.0.ebuild

Dependencies of gnome-core-apps and gnome-extra-apps require cups or colord use flags set. gnome-control-center and gnome-settings-daemon dropped these flags in this overlay as they are now unconditionally required, however this breaks the dependency calculation. I suggest to just re-add the use flags without any real purpose to simplify the dependency calculation with the ebuilds from the overlay.

control-center, settings-daemon: add cups and colord use flag for compat

---

x11-libs/gtksourceview/gtksourceview-4.3.1.ebuild

Otherwise build fails, when Vala USE is disabled.

x11-libs/gtksourceview:4: correctly set meson args

---

gnome-base/librsvg/librsvg-2.45.90.ebuild

it seems to have been possible to prefere gtk2 over gtk3 in the past, but that's no more.

gnome-base/librsvg: --without-gtk3 is gone

---

gnome-base/librsvg/librsvg-2.45.90.ebuild

this is actually important for cross compile with emerge wrappers from crossdev.

gnome-base/librsvg: dev-lang/rust is a build time dependency

---

gnome-base/librsvg/librsvg-2.45.90.ebuild
gnome-base/librsvg/librsvg-2.45.92.ebuild

COMPILING.md says to go for a minimum of v1.34.x

gnome-base/librsvg: bump minimal rust to upstreams reference

---

gnome-base/librsvg/librsvg-2.45.92.ebuild

librsvg expects a full i686-unknown-linux-gnu std to be available to allow multilib compile with rust-bin 
it seems to pull in all the correct options. But please somebody test this, I don't use librsvg with multilib on my own! @jrevillard 
```
USE="abi_x86_32"  emerge -pv =librsvg-2.45.92::gnome-next
These are the packages that would be merged, in order:
Calculating dependencies... done!
[ebuild   R    ] dev-libs/lzo-2.10:2::gentoo  USE="(split-usr) static-libs -examples" ABI_X86="32* (64) (-x32)" 0 KiB
[ebuild   R   ~] dev-lang/rust-bin-1.37.0:stable::gentoo  USE="rustfmt -clippy -doc -libressl" ABI_X86="32* (64) (-x32)" CPU_FLAGS_X86="sse2" 0 KiB
[ebuild  N    ~] dev-lang/rust-std-bin-1.37.0:stable::gnome-next  ABI_X86="32" CPU_FLAGS_X86="sse2" 0 KiB
[ebuild   R    ] …
```

gnome-base/librsvg: pull in rust-std-bin along with rust-bin

---

gnome-base/gnome-settings-daemon/files/gnome-settings-daemon-3.33.0-plugins-Add-systemd-user-service-files-for-all-the-p.patch
gnome-base/gnome-settings-daemon/files/gnome-settings-daemon-3.33.0-xsettings-Ensure-plugin-is-started-after-the-shell.patch
gnome-base/gnome-settings-daemon/files/gnome-settings-daemon-3.33.0-xsettings-Make-it-able-to-run-on-demand.patch
gnome-base/gnome-settings-daemon/gnome-settings-daemon-3.33.0.ebuild

These patches (from upstream Git, no release tag as of my writing this)
set up systemd services for the various components of
GNOME-Settings-Daemon and ensure that they're started *after* XWayland
(if GNOME is riding atop Wayland and not an XOrg server).  This seems to
be necessary when starting a GNOME session with bleeding-edge
Mutter/GNOME-Shell on a systemd-managed Linux instance, and is
definitely neccessary when starting any GNOME session (including via
GDM) on the same system type when sys-apps/dbus is merged with the
'user-session' USE flag set.  Without full systemd service support,
gnome-settings-daemon components can freak out when they don't see
XWayland, and if they fail to start, the whole GNOME session fails.

Add systemd patchset to gnome-settings-daemon

---

gnome-base/gdm/gdm-3.34.1.ebuild
gnome-base/gnome-keyring/gnome-keyring-3.34.0.ebuild

Please merge ASAP, virtual/pam is already masked in gx86

gnome-base/*: migrate to sys-libs/pam

---

gnome-extra/sushi/sushi-3.34.0.ebuild

Closes: https://github.com/Heather/gentoo-gnome/issues/328

gnome-extra/sushi: workaround sandbox violation

---

gnome-base/librsvg/librsvg-2.47.1.ebuild

upstream demands so in compile.md

gnome-base/librsvg: raise minimal rust dep to 1.36.0

---

dev-lang/rust-std-bin/rust-std-bin-1.37.0.ebuild

current stable is rust-bin-1.37.0, keep that in sync.

dev-lang/rust-std-bin: sync keywords with tree

---

gnome-extra/evolution-data-server/evolution-data-server-3.34.2.ebuild

Since commit 1c6e0593af245703205da5109eb46721cc0e542a is glib merged
into introspection USE flag.

gnome-extra/evolution-data-server: fix dependency on ical

---

dev-util/gtk-doc/gtk-doc-1.30.ebuild

otherwise librsvg can't be build with USE="gtk-doc"

dev-util/gtk-doc: add missing pygments for building gtk-doc

---

gnome-base/librsvg/librsvg-2.47.2.ebuild

virtual/cargo is going away, see https://bugs.gentoo.org/695698

gnome-base/librsvg: remove virtual/cargo

---

gnome-base/gnome-shell/gnome-shell-3.36.1.ebuild

No magic, just buildsystem yelled at me due to fact gnome-desktop hasn't been updated :)

gnome-base/gnome-shell: raise gnome-desktop dep

---

dev-libs/gjs/gjs-1.65.1.build

WIP because spidermonkey:68 isn't keyworded in gx86 yet.
- depends on spidermonkey:68

dev-libs/gjs: bump to 1.65.1

---

dev-util/sysprof/sysprof-3.36.0.ebuild

dev-util/sysprof: it looks like it isn't installed by sysprof-capture

---

gnome-base/gnome-shell/gnome-shell-3.36.3.ebuild
profiles/package.unmask

Otherwise it will run with an old version of gjs and spidermonkey.
This causes a runtime error:
(JS ERROR: TypeError: keywords.split(...).map(...).flat is not a function)

Fix gnome-shell dependencies
